version: '3.8'

services:
  webgl:
    container_name: unity-webgl-navigation
    image: unity-webgl-navigation
    build: .
    ports:
      - "8080:80"
  node:
    container_name: node-server
    image: node-server
    build: './node'
    volumes:
      - .:/src
    command: npm start
    ports:
      - "3000:3000"